"""Spec-Kit adapter — maps the real `github/spec-kit` layout to normalized Artifacts.

Layout (verified against spec-kit templates):
    specs/<feature-id>/spec.md | plan.md | tasks.md
                       research.md | data-model.md | quickstart.md
                       contracts/*
    .specify/memory/constitution.md
    .specify/templates/*-template.md   (used to derive required sections)
"""

from __future__ import annotations

from pathlib import Path

from ..model import Artifact, ArtifactType
from .base import parse_sections, required_sections_from_template

# Filenames Spec-Kit produces, mapped to artifact types.
_FILENAME_TYPES: dict[str, ArtifactType] = {
    "spec.md": ArtifactType.SPEC,
    "plan.md": ArtifactType.PLAN,
    "tasks.md": ArtifactType.TASKS,
    "research.md": ArtifactType.RESEARCH,
    "data-model.md": ArtifactType.DATA_MODEL,
    "quickstart.md": ArtifactType.QUICKSTART,
    "constitution.md": ArtifactType.CONSTITUTION,
}

# Fallback required-section lists (level-2 headings) when no template is on disk.
# Derived from the real spec-kit *-template.md files.
_DEFAULT_REQUIRED: dict[ArtifactType, list[str]] = {
    ArtifactType.SPEC: ["User Scenarios", "Requirements", "Success Criteria"],
    ArtifactType.PLAN: ["Summary", "Technical Context", "Constitution Check", "Project Structure"],
    ArtifactType.TASKS: ["Dependencies"],
    ArtifactType.CONSTITUTION: ["Core Principles", "Governance"],
}

# Map an artifact type to its template filename stem.
_TEMPLATE_STEM: dict[ArtifactType, str] = {
    ArtifactType.SPEC: "spec",
    ArtifactType.PLAN: "plan",
    ArtifactType.TASKS: "tasks",
    ArtifactType.CONSTITUTION: "constitution",
    ArtifactType.CHECKLIST: "checklist",
}


class SpecKitAdapter:
    """ArtifactAdapter implementation for GitHub Spec-Kit."""

    name = "speckit"

    def detect(self, root: Path) -> bool:
        if (root / ".specify").is_dir():
            return True
        # Or a specs/<id>/spec.md anywhere shallow.
        specs = root / "specs"
        if specs.is_dir() and any(specs.glob("*/spec.md")):
            return True
        # Or root IS a single feature dir (specs/<id>/ itself) — lets users narrow
        # a review to one feature (`sddgrade review specs/<feature>`), which is the
        # recommended way to stay under the --api input budget on large corpora.
        if (root / "spec.md").is_file():
            return True
        return False

    def classify(self, path: Path) -> ArtifactType:
        name = path.name.lower()
        if name in _FILENAME_TYPES:
            return _FILENAME_TYPES[name]
        if "contracts" in {p.lower() for p in path.parts}:
            return ArtifactType.CONTRACT
        if "checklist" in name:
            return ArtifactType.CHECKLIST
        return ArtifactType.UNKNOWN

    def _feature_id(self, path: Path, root: Path) -> str | None:
        """The `specs/<feature-id>/...` segment, if any."""
        try:
            rel = path.resolve().relative_to((root / "specs").resolve())
        except ValueError:
            # Root may itself be a feature dir (single-feature review): use its name.
            if (root / "spec.md").is_file():
                return root.resolve().name
            return None
        return rel.parts[0] if rel.parts else None

    def discover(self, root: Path) -> list[Path]:
        found: list[Path] = []
        specs = root / "specs"
        if specs.is_dir():
            for feature_dir in sorted(p for p in specs.iterdir() if p.is_dir()):
                found.extend(self._feature_files(feature_dir))
        elif (root / "spec.md").is_file():
            # Root is a single feature dir (specs/<id>/) — the narrow-review path.
            found.extend(self._feature_files(root))
        constitution = root / ".specify" / "memory" / "constitution.md"
        if constitution.is_file():
            found.append(constitution)
        return found

    def _feature_files(self, feature_dir: Path) -> list[Path]:
        """All reviewable files of one specs/<feature-id>/ directory."""
        found: list[Path] = []
        for known in _FILENAME_TYPES:
            f = feature_dir / known
            if f.is_file() and known != "constitution.md":
                found.append(f)
        # Checklists (e.g. generated by /speckit.checklist).
        found.extend(sorted(feature_dir.glob("*checklist*.md")))
        # Contracts.
        contracts = feature_dir / "contracts"
        if contracts.is_dir():
            found.extend(sorted(f for f in contracts.iterdir() if f.is_file()))
        return found

    def parse(self, path: Path, root: Path) -> Artifact:
        text = path.read_text(encoding="utf-8", errors="replace")
        atype = self.classify(path)
        return Artifact(
            path=str(path),
            type=atype,
            feature_id=self._feature_id(path, root),
            raw=text,
            sections=parse_sections(text),
        )

    def required_sections(self, artifact_type: ArtifactType, root: Path) -> list[str]:
        stem = _TEMPLATE_STEM.get(artifact_type)
        if stem:
            template = root / ".specify" / "templates" / f"{stem}-template.md"
            if template.is_file():
                derived = required_sections_from_template(
                    template.read_text(encoding="utf-8", errors="replace")
                )
                if derived:
                    return derived
        return _DEFAULT_REQUIRED.get(artifact_type, [])
